create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  avatar_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.survival_cache (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tmdb_id bigint not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  title text not null,
  poster_path text,
  added_at timestamptz not null default now(),
  unique (user_id, tmdb_id, media_type)
);

create table if not exists public.history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id bigint not null,
  type text not null check (type in ('movie', 'tv')),
  title text not null,
  poster_path text,
  created_at timestamptz not null default now(),
  unique (user_id, content_id, type)
);

alter table public.profiles enable row level security;
alter table public.survival_cache enable row level security;
alter table public.history enable row level security;

create policy "Users can read their own profile" on public.profiles
  for select using (auth.uid() = id);
create policy "Users can create their own profile" on public.profiles
  for insert with check (auth.uid() = id);
create policy "Users can update their own profile" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "Users can read their own watchlist" on public.survival_cache
  for select using (auth.uid() = user_id);
create policy "Users can add to their own watchlist" on public.survival_cache
  for insert with check (auth.uid() = user_id);
create policy "Users can delete from their own watchlist" on public.survival_cache
  for delete using (auth.uid() = user_id);

create policy "Users can read their own history" on public.history
  for select using (auth.uid() = user_id);
create policy "Users can add to their own history" on public.history
  for insert with check (auth.uid() = user_id);
create policy "Users can delete from their own history" on public.history
  for delete using (auth.uid() = user_id);
