create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  username text unique,
  username_lower text unique,
  avatar_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  comment_key text not null,
  author text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.survival_cache (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tmdb_id bigint not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  title text not null,
  poster_path text,
  added_at timestamptz not null default now(),
  unique (user_id, tmdb_id, media_type)
);

create table if not exists public.history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id bigint not null,
  type text not null check (type in ('movie', 'tv')),
  title text not null,
  poster_path text,
  created_at timestamptz not null default now(),
  unique (user_id, content_id, type)
);

alter table public.profiles enable row level security;
alter table public.comments enable row level security;
alter table public.survival_cache enable row level security;
alter table public.history enable row level security;

create policy "Public read profiles" on public.profiles for select
  using (true);
-- NOTE: email column should NOT be exposed via client queries.
-- Use supabase.from('profiles').select('id, username, username_lower') to avoid leaking emails.
create policy "Users can manage profile" on public.profiles for all using (auth.uid() = id);

create policy "Public read comments" on public.comments for select using (true);
create policy "Authenticated users can post comments" on public.comments
  for insert with check (auth.uid() is not null);
create policy "Users can delete own comments" on public.comments for delete using (auth.uid() = user_id);

create policy "Users can read watchlist" on public.survival_cache for select using (auth.uid() = user_id);
create policy "Users can add to watchlist" on public.survival_cache for insert with check (auth.uid() = user_id);
create policy "Users can delete from watchlist" on public.survival_cache for delete using (auth.uid() = user_id);

create policy "Users can read history" on public.history for select using (auth.uid() = user_id);
create policy "Users can add to history" on public.history for insert with check (auth.uid() = user_id);
create policy "Users can delete from history" on public.history for delete using (auth.uid() = user_id);

-- Watchlist status: want (queue) / watching (TV with episodes logged) / watched (seen or marked complete)
alter table public.survival_cache add column if not exists status text not null default 'want' check (status in ('want', 'watching', 'watched'));
alter table public.survival_cache add column if not exists watched_at timestamptz;

create table if not exists public.watched_episodes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tmdb_id bigint not null,
  season int not null,
  episode int not null,
  watched_at timestamptz not null default now(),
  unique (user_id, tmdb_id, season, episode)
);

alter table public.watched_episodes enable row level security;

create policy "Users can update watchlist" on public.survival_cache for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can update history" on public.history for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can read watched episodes" on public.watched_episodes for select using (auth.uid() = user_id);
create policy "Users can add watched episodes" on public.watched_episodes for insert with check (auth.uid() = user_id);
create policy "Users can update watched episodes" on public.watched_episodes for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can remove watched episodes" on public.watched_episodes for delete using (auth.uid() = user_id);
